import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parseArgs } from "../config.js";
import type { SolveCommandDeps } from "./run.js";

type InitProfile = "local" | "team" | "ci";
type InitProvider = "deepseek" | "glm";
type InitPermissionMode = "ask" | "yolo";
type InitSandboxMode = "read-only" | "workspace-write" | "danger-full-access" | "policy-only" | "external";
type InitValidationMode = "off" | "auto";

interface InitConfig {
  workspace: string;
  profile: InitProfile;
  provider: InitProvider;
  model?: string;
  permissionMode: InitPermissionMode;
  sandboxMode: InitSandboxMode;
  sandboxRequired: boolean;
  validationMode: InitValidationMode;
}

function stdout(deps: SolveCommandDeps): NodeJS.WritableStream {
  return deps.stdout ?? process.stdout;
}

function stderr(deps: SolveCommandDeps): NodeJS.WritableStream {
  return deps.stderr ?? process.stderr;
}

function printHelp(deps: SolveCommandDeps): void {
  stdout(deps).write(`agent init [flags]

Create a Sigma workspace configuration at .agent/config.toml.

Flags:
  --workspace <path>              Workspace to initialize (default: cwd)
  --profile <local|team|ci>       Product profile to write (default: local)
  --provider <deepseek|glm>       Default model provider (default: deepseek)
  --model <name>                  Optional default model name
  --permission-mode <ask|yolo>    Tool permission mode
  --sandbox <mode>                Sandbox mode
  --sandbox-required              Fail closed if OS sandbox is unavailable
  --validation-mode <off|auto>    Validation mode
  --force                         Overwrite an existing .agent/config.toml
  --json                          Print a JSON report
`);
}

function stringFlag(flags: Record<string, string | boolean>, name: string): string | undefined {
  const value = flags[name];
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function profileValue(value: string | undefined): InitProfile {
  if (!value) return "local";
  if (value === "local" || value === "team" || value === "ci") return value;
  throw new Error(`Unsupported profile '${value}'. Use local, team, or ci.`);
}

function providerValue(value: string | undefined): InitProvider {
  if (!value) return "deepseek";
  if (value === "deepseek" || value === "glm") return value;
  throw new Error(`Unsupported provider '${value}'. Use deepseek or glm.`);
}

function permissionModeValue(value: string | undefined, profile: InitProfile): InitPermissionMode {
  if (!value) return profile === "ci" ? "yolo" : "ask";
  if (value === "ask" || value === "yolo") return value;
  throw new Error(`Unsupported permission mode '${value}'. Use ask or yolo.`);
}

function sandboxModeValue(value: string | undefined): InitSandboxMode {
  if (!value) return "workspace-write";
  if (value === "read-only" || value === "workspace-write" || value === "danger-full-access" || value === "policy-only" || value === "external") {
    return value;
  }
  throw new Error(`Unsupported sandbox '${value}'. Use read-only, workspace-write, danger-full-access, policy-only, or external.`);
}

function validationModeValue(value: string | undefined): InitValidationMode {
  if (!value) return "auto";
  if (value === "off" || value === "auto") return value;
  throw new Error(`Unsupported validation mode '${value}'. Use off or auto.`);
}

function boolFlag(flags: Record<string, string | boolean>, name: string): boolean {
  return flags[name] === true || flags[name] === "true";
}

function initConfig(flags: Record<string, string | boolean>): InitConfig {
  const profile = profileValue(stringFlag(flags, "profile"));
  return {
    workspace: path.resolve(stringFlag(flags, "workspace") ?? process.cwd()),
    profile,
    provider: providerValue(stringFlag(flags, "provider")),
    model: stringFlag(flags, "model"),
    permissionMode: permissionModeValue(stringFlag(flags, "permission-mode"), profile),
    sandboxMode: sandboxModeValue(stringFlag(flags, "sandbox")),
    sandboxRequired: boolFlag(flags, "sandbox-required") || profile === "team" || profile === "ci",
    validationMode: validationModeValue(stringFlag(flags, "validation-mode"))
  };
}

function quoted(value: string): string {
  return JSON.stringify(value);
}

function configToml(config: InitConfig): string {
  const modelLine = config.model ? `model = ${quoted(config.model)}\n` : "# model = \"provider-default\"\n";
  const outputLine = config.profile === "ci" ? "output_format = \"json\"\nquiet = true\n" : "";
  return `# Sigma Code workspace config generated by agent init.
# Profile: ${config.profile}

[run]
provider = ${quoted(config.provider)}
${modelLine}permission_mode = ${quoted(config.permissionMode)}
max_turns = 20
max_wall_time_sec = 900
${outputLine}
[validation]
mode = ${quoted(config.validationMode)}
retry_limit = 0
final_evidence_mode = "auto"

[sandbox]
mode = ${quoted(config.sandboxMode)}
backend = "auto"
required = ${config.sandboxRequired ? "true" : "false"}

[sandbox.network]
mode = "restricted"
allow_localhost = true

[context]
mode = "repo-map"
repo_map_max_chars = 20000
compaction_mode = "model-sub-session"

[skills]
mode = "auto"

[subagents]
enabled = true
background_enabled = true

[review]
anti_gaming = true

[tui]
stream_ui = true
`;
}

export async function runInitCommand(argv: string[], deps: SolveCommandDeps = {}): Promise<number> {
  const { flags } = parseArgs(argv);
  if (flags.help === true || flags.h === true) {
    printHelp(deps);
    return 0;
  }

  const json = flags.json !== undefined;
  let config: InitConfig;
  try {
    config = initConfig(flags);
  } catch (error) {
    stderr(deps).write(`${error instanceof Error ? error.message : String(error)}\n`);
    return 1;
  }

  const agentDir = path.join(config.workspace, ".agent");
  const configPath = path.join(agentDir, "config.toml");
  const force = boolFlag(flags, "force");

  try {
    await mkdir(agentDir, { recursive: true });
    if (!force) {
      try {
        await readFile(configPath, "utf8");
        const message = `${configPath} already exists. Use --force to overwrite.`;
        if (json) stdout(deps).write(`${JSON.stringify({ ok: false, configPath, message })}\n`);
        else stderr(deps).write(`${message}\n`);
        return 1;
      } catch (error) {
        const code = (error as { code?: unknown }).code;
        if (code !== "ENOENT") throw error;
      }
    }

    await writeFile(configPath, configToml(config), "utf8");
    const nextSteps = [
      "Set the provider API key in your shell.",
      "Run: agent doctor --workspace <workspace> --check-api",
      "Run: agent tui --workspace <workspace>"
    ];
    if (json) {
      stdout(deps).write(`${JSON.stringify({
        ok: true,
        configPath,
        profile: config.profile,
        provider: config.provider,
        sandboxRequired: config.sandboxRequired,
        nextSteps
      })}\n`);
    } else {
      stdout(deps).write([
        `initialized ${configPath}`,
        `profile=${config.profile}`,
        `provider=${config.provider}`,
        `sandbox_required=${config.sandboxRequired}`,
        "next:",
        `  ${nextSteps[0]}`,
        `  ${nextSteps[1]}`,
        `  ${nextSteps[2]}`
      ].join("\n") + "\n");
    }
    return 0;
  } catch (error) {
    stderr(deps).write(`${error instanceof Error ? error.message : String(error)}\n`);
    return 1;
  }
}
