packages:
  - "packages/*"
supportedArchitectures:
  os:
    - current
    - linux
    - win32
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
onlyBuiltDependencies:
  - esbuild
  - tree-sitter
  - tree-sitter-go
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-rust
  - tree-sitter-typescript
allowBuilds:
  esbuild: true
  tree-sitter: true
  tree-sitter-go: true
  tree-sitter-javascript: true
  tree-sitter-python: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
