import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import type { ModelClient, ModelRequest, ModelResponse } from "../packages/agent-ai/src/index.js";
import { loadProjectInstructions, runAgent } from "../packages/agent-core/src/index.js";

class CaptureModel implements ModelClient {
  readonly provider = "deepseek" as const;
  readonly model = "fake-context-model";
  readonly requests: ModelRequest[] = [];

  async complete(req: ModelRequest): Promise<ModelResponse> {
    this.requests.push(req);
    return { message: { role: "assistant", content: "done" } };
  }
}

async function workspace(): Promise<string> {
  return await mkdtemp(path.join(os.tmpdir(), "sigma-context-"));
}

describe("project instructions and repo map context", () => {
  it("loads root AGENTS.md", async () => {
    const dir = await workspace();
    await writeFile(path.join(dir, "AGENTS.md"), "Use local style.", "utf8");
    const loaded = await loadProjectInstructions({ workspacePath: dir });
    expect(loaded.sources).toEqual(["AGENTS.md"]);
    expect(loaded.content).toContain("Use local style.");
  });

  it("uses AGENTS.override.md over AGENTS.md in the same directory", async () => {
    const dir = await workspace();
    await writeFile(path.join(dir, "AGENTS.md"), "base", "utf8");
    await writeFile(path.join(dir, "AGENTS.override.md"), "override", "utf8");
    const loaded = await loadProjectInstructions({ workspacePath: dir });
    expect(loaded.sources).toEqual(["AGENTS.override.md"]);
    expect(loaded.content).toContain("override");
    expect(loaded.content).not.toContain("\nbase");
  });

  it("falls back to SIGMA.md and respects max bytes", async () => {
    const dir = await workspace();
    await writeFile(path.join(dir, "SIGMA.md"), "abcdef", "utf8");
    const loaded = await loadProjectInstructions({ workspacePath: dir, maxBytes: 3 });
    expect(loaded.sources).toEqual(["SIGMA.md"]);
    expect(loaded.content).toContain("abc");
    expect(loaded.content).not.toContain("def");
  });

  it("can be disabled and rejects working directories outside the workspace", async () => {
    const dir = await workspace();
    await writeFile(path.join(dir, "AGENTS.md"), "hidden", "utf8");
    await expect(loadProjectInstructions({ workspacePath: dir, enabled: false })).resolves.toEqual({
      content: "",
      sources: []
    });
    await expect(loadProjectInstructions({ workspacePath: dir, workingDirectory: "../outside" })).rejects.toThrow(
      "outside the workspace"
    );
  });

  it("adds project instructions and repo map to the system prompt when enabled", async () => {
    const dir = await workspace();
    await mkdir(path.join(dir, "src"), { recursive: true });
    await writeFile(path.join(dir, "AGENTS.md"), "Project rule: verify before editing.", "utf8");
    await writeFile(path.join(dir, "package.json"), JSON.stringify({ scripts: { test: "vitest run" } }), "utf8");
    await writeFile(path.join(dir, "src", "index.ts"), "export function hello() { return 'hi'; }\n", "utf8");
    const model = new CaptureModel();

    await runAgent({
      instruction: "finish",
      workspacePath: dir,
      modelClient: model,
      contextMode: "repo-map",
      repoMapMaxChars: 5000
    });

    const system = model.requests[0].messages[0];
    expect(system.role).toBe("system");
    expect(system.content).toContain("Project instructions loaded from:");
    expect(system.content).toContain("Project rule: verify before editing.");
    expect(system.content).toContain("Repository map generated by Sigma");
    expect(system.content).toContain("root scripts: test");
    expect(system.content).toContain("src/index.ts: hello");
    expect(model.requests[0].cacheHints?.some((hint) => hint.kind === "system")).toBe(true);
  });

  it("omits repo map when context mode is off", async () => {
    const dir = await workspace();
    const model = new CaptureModel();
    await runAgent({ instruction: "finish", workspacePath: dir, modelClient: model, contextMode: "off" });
    expect(model.requests[0].messages[0].content).not.toContain("Repository map generated by Sigma");
  });
});
