/* Generated by scripts/generate-sigma-manifest.mjs. Do not edit. */
export const SIGMA_PROJECT_FACTS = {
  "schemaVersion": 1,
  "productVersion": "3.0.0-rc.1",
  "toolchains": {
    "node": "26.4.0",
    "pnpm": "11.7.0",
    "rust": "1.96.0",
    "rustCoverage": "nightly-2026-07-01"
  },
  "release": {
    "targets": [
      "linux-x64",
      "win32-x64"
    ],
    "windowsNodePatch": {
      "kind": "windows_appcontainer_node",
      "patchId": "node-v26.4.0-win-x64-libuv-local-pipe-v2",
      "reason": "Use AppContainer-local libuv pipe names for captured stdio and Node IPC.",
      "nodeVersion": "v26.4.0",
      "targetPlatform": "win32",
      "targetArch": "x64",
      "sourceSha256": "3193d7f751b8a07bd4acc70e81946ae9c6efdee83e07ad1c8d0e4089df7c5cef",
      "unsignedPatchedSha256": "b30b9546e4c9fddffbd4054ef4a78cdd76b42a8496bfb6308a7966bae37fea8f",
      "normalizedContentSha256": "6345a8101a378aea8f004210fe3924b6bcc77029abd35d9a86fa88e65a65bf35"
    }
  },
  "evaluation": {
    "provider": "deepseek",
    "model": "deepseek-v4-pro"
  }
} as const;
